// Traits Data - Complete List
const traitsData = [
  {"name": "Upper Hand", "category": "Global", "type": "positive"},
  {"name": "Stable Energy", "category": "Global", "type": "positive"},
  {"name": "Stable Vitality", "category": "Global", "type": "positive"},
  {"name": "Optimist 5", "category": "Global", "type": "positive"},
  {"name": "Covert Energ 5", "category": "Global", "type": "positive"},
  {"name": "Power Rewind 2", "category": "Global", "type": "positive"},
  {"name": "Rise and Shine 5", "category": "Global", "type": "positive"},
  {"name": "Growing Pains 3", "category": "Global", "type": "mixed"},
  {"name": "Cheer Up 3", "category": "Global", "type": "mixed"},
  {"name": "Worn-out 2", "category": "Global", "type": "negative"},
  {"name": "Feeling Blue 2", "category": "Global", "type": "negative"},
  {"name": "Psychic Kid", "category": "Combat", "type": "positive"},
  {"name": "Crack Shot", "category": "Combat", "type": "positive"},
  {"name": "Heavy and Solid", "category": "Combat", "type": "positive"},
  {"name": "Run Fast", "category": "Combat", "type": "positive"},
  {"name": "Power King", "category": "Combat", "type": "mixed"},
  {"name": "Brute Force", "category": "Combat", "type": "mixed"},
  {"name": "Long Distance Runner", "category": "Combat", "type": "mixed"},
  {"name": "Save Energy", "category": "Combat", "type": "mixed"},
  {"name": "Vegatative Calm", "category": "Combat", "type": "mixed"},
  {"name": "Beast of Burden", "category": "Combat", "type": "positive"},
  {"name": "City Folk", "category": "Combat", "type": "positive"},
  {"name": "Durability", "category": "Combat", "type": "positive"},
  {"name": "Move More, Live Better", "category": "Combat", "type": "positive"},
  {"name": "Street Rascal", "category": "Combat", "type": "positive"},
  {"name": "Two-Shift System", "category": "Combat", "type": "positive"},
  {"name": "Stay Indoors", "category": "Combat", "type": "negative"},
  {"name": "Wellbeing", "category": "Combat", "type": "positive"},
  {"name": "Sedantary", "category": "Combat", "type": "negative"},
  {"name": "Lighten Your Mind", "category": "Combat", "type": "positive"},
  {"name": "Elemental DMG Reduction", "category": "SCP", "type": "positive"},
  {"name": "Physical DMG Reduction", "category": "SCP", "type": "positive"},
  {"name": "Elemental DMG Bonus", "category": "SCP", "type": "positive"},
  {"name": "Physical DMG Bonus", "category": "SCP", "type": "positive"},
  {"name": "Attack", "category": "SCP", "type": "positive"},
  {"name": "Attack Percentage", "category": "SCP", "type": "positive"},
  {"name": "HP", "category": "SCP", "type": "positive"},
  {"name": "HP Percentage", "category": "SCP", "type": "positive"},
  {"name": "Crit Damage", "category": "SCP", "type": "positive"},
  {"name": "Crit Rate", "category": "SCP", "type": "positive"},
  {"name": "Anti-Burnout", "category": "Territory", "type": "positive"},
  {"name": "Dream Wild", "category": "Territory", "type": "positive"},
  {"name": "A World of Charm", "category": "Territory", "type": "positive"},
  {"name": "Sweet Talk", "category": "Territory", "type": "positive"},
  {"name": "Hydrophilic", "category": "Territory", "type": "positive"},
  {"name": "Devoted laborer", "category": "Territory", "type": "mixed"},
  {"name": "Workaholic", "category": "Territory", "type": "mixed"},
  {"name": "Water Dormancy", "category": "Territory", "type": "positive"},
  {"name": "Voluntary Overtime", "category": "Territory", "type": "positive"},
  {"name": "Living Map", "category": "Territory", "type": "positive"},
  {"name": "Stardust Affinity", "category": "Territory", "type": "positive"},
  {"name": "OnePlus", "category": "Territory", "type": "mixed"},
  {"name": "Imperfect Endless Motion", "category": "Territory", "type": "positive"},
  {"name": "Lazy Bones", "category": "Territory", "type": "negative"},
  {"name": "Panovision", "category": "Territory", "type": "negative"},
  {"name": "Slacking Off", "category": "Territory", "type": "negative"},
  {"name": "Baffling Behavior", "category": "Territory", "type": "negative"},
  {"name": "Holding the Team Back", "category": "Territory", "type": "negative"},
  {"name": "Heartthrob", "category": "Territory", "type": "mixed"},
  {"name": "Snooze Afficionado", "category": "Territory", "type": "mixed"},
  {"name": "Toxicologist", "category": "Territory", "type": "mixed"},
  {"name": "An old Hand Knows the Ropes", "category": "Territory", "type": "mixed"},
  {"name": "Gilded Oracle", "category": "Territory", "type": "mixed"},
  {"name": "Wild Wood Spirit", "category": "Territory", "type": "mixed"},
  {"name": "Waste Not", "category": "Crafting", "type": "positive"},
  {"name": "Leftover", "category": "Crafting", "type": "mixed"},
  {"name": "Byproduct", "category": "Crafting", "type": "positive"},
  {"name": "Efficiency Above All", "category": "Crafting", "type": "mixed"},
  {"name": "Stardust Empowerment", "category": "Crafting", "type": "positive"},
  {"name": "Speed Up", "category": "Crafting", "type": "positive"},
  {"name": "Productivity First", "category": "Crafting", "type": "positive"},
  {"name": "Collection +1", "category": "Crafting", "type": "mixed"},
  {"name": "Eureka Moment", "category": "Crafting", "type": "mixed"},
  {"name": "The Joy of Slacking Off", "category": "Crafting", "type": "mixed"},
  {"name": "Unhinged Production", "category": "Crafting", "type": "mixed"},
  {"name": "Unplanned Production", "category": "Crafting", "type": "mixed"},
  {"name": "Big Cup", "category": "Crafting", "type": "positive"},
  {"name": "Buy 1 Get 2", "category": "Crafting", "type": "positive"},
  {"name": "Come As One", "category": "Crafting", "type": "positive"},
  {"name": "Efficiency First", "category": "Crafting", "type": "positive"},
  {"name": "Medium Cup", "category": "Crafting", "type": "positive"},
  {"name": "Mineral Talent", "category": "Crafting", "type": "positive"},
  {"name": "One More Bottle", "category": "Crafting", "type": "positive"},
  {"name": "Out of Scratch", "category": "Crafting", "type": "positive"},
  {"name": "Piece of Cake", "category": "Crafting", "type": "positive"},
  {"name": "Super Big Cup", "category": "Crafting", "type": "positive"},
  {"name": "The Last Night", "category": "Crafting", "type": "positive"},
  {"name": "Work of Proficiency", "category": "Crafting", "type": "positive"},
  {"name": "Clumsy", "category": "Crafting", "type": "negative"},
  {"name": "No Such Thing As a Small Cup", "category": "Crafting", "type": "negative"},
  {"name": "Lazy", "category": "Crafting", "type": "negative"},
  {"name": "Smooth Sheep Rustler", "category": "Crafting", "type": "mixed"},
  {"name": "Moonlight Assault", "category": "Animal", "type": "positive"},
  {"name": "Feline Creatures", "category": "Animal", "type": "positive"},
  {"name": "Brute Force Rules", "category": "Animal", "type": "positive"},
  {"name": "Foul Symbiosis", "category": "Animal", "type": "positive"},
  {"name": "Polar Beast", "category": "Animal", "type": "positive"},
  {"name": "Top Grunt", "category": "Animal", "type": "positive"},
  {"name": "Nightmare Waters", "category": "Animal", "type": "positive"},
  {"name": "Mind Massage", "category": "Animal", "type": "positive"},
  {"name": "Herbivore", "category": "Animal", "type": "positive"},
  {"name": "Pollution Adaptation", "category": "Furniture", "type": "positive"},
  {"name": "Precision Moment", "category": "Furniture", "type": "positive"},
  {"name": "Master of Temperatures", "category": "Furniture", "type": "positive"},
  {"name": "Knights of the Round Table", "category": "Furniture", "type": "positive"},
  {"name": "Warm Flame", "category": "Furniture", "type": "positive"},
  {"name": "Eureka Moment", "category": "Furniture", "type": "positive"},
  {"name": "Extra Load", "category": "Furniture", "type": "positive"},
  {"name": "Music Resonance", "category": "Furniture", "type": "positive"},
  {"name": "Clean and Hygienic", "category": "Furniture", "type": "positive"},
  {"name": "Neon Flicker", "category": "Furniture", "type": "positive"},
  {"name": "Milk Sugar", "category": "Variation", "type": "variation"},
  {"name": "Marine Star", "category": "Variation", "type": "variation"},
  {"name": "Spring Rose", "category": "Variation", "type": "variation"},
  {"name": "Ancient Scroll", "category": "Variation", "type": "variation"},
  {"name": "Glistening Blue", "category": "Variation", "type": "variation"},
  {"name": "Starry Night", "category": "Variation", "type": "variation"},
  {"name": "Aquarius", "category": "Variation", "type": "variation"},
  {"name": "Gluttonous Bunny", "category": "Variation", "type": "variation"},
  {"name": "Dark Rebel", "category": "Variation", "type": "variation"},
  {"name": "Alice", "category": "Variation", "type": "variation"},
  {"name": "Violet Robe", "category": "Variation", "type": "variation"},
  {"name": "Extra Large", "category": "Variation", "type": "variation"},
  {"name": "Green Touch", "category": "Variation", "type": "variation"},
  {"name": "Green Field", "category": "Variation", "type": "variation"},
  {"name": "Copper Green", "category": "Variation", "type": "variation"},
  {"name": "Tin Soldier", "category": "Variation", "type": "variation"},
  {"name": "Twisted Fairy Tale", "category": "Variation", "type": "variation"},
  {"name": "Displaced Fairy Tale", "category": "Variation", "type": "variation"},
  {"name": "Wood Yellow", "category": "Variation", "type": "variation"},
  {"name": "Clear Lake", "category": "Variation", "type": "variation"},
  {"name": "Purple (Power Rewind)", "category": "Variation", "type": "variation"},
  {"name": "Date Brown", "category": "Variation", "type": "variation"},
  {"name": "Golden Era", "category": "Variation", "type": "variation"},
  {"name": "Silver Gentleman", "category": "Variation", "type": "variation"},
  {"name": "Diamond Duke", "category": "Variation", "type": "variation"},
  {"name": "Diamond Count", "category": "Variation", "type": "variation"},
  {"name": "Ocean Blue", "category": "Variation", "type": "variation"},
  {"name": "Christmas", "category": "Variation", "type": "variation"},
  {"name": "Sugar Guard", "category": "Variation", "type": "variation"},
  {"name": "Admiral", "category": "Variation", "type": "variation"},
  {"name": "Elegant Purple", "category": "Variation", "type": "variation"},
  {"name": "Dappled Light", "category": "Variation", "type": "variation"},
  {"name": "Good Fortune", "category": "Variation", "type": "variation"},
  {"name": "Moonlit Jewels", "category": "Variation", "type": "variation"},
  {"name": "Heavy Ginger", "category": "Variation", "type": "variation"},
  {"name": "Emerald", "category": "Variation", "type": "variation"},
  {"name": "Fortune Dice", "category": "Variation", "type": "variation"},
  {"name": "Pure Gold", "category": "Variation", "type": "variation"},
  {"name": "Prism", "category": "Variation", "type": "variation"},
  {"name": "Radiant Flourish", "category": "Variation", "type": "variation"},
  {"name": "Pumpkin Lantern", "category": "Variation", "type": "variation"},
  {"name": "Pharaoh", "category": "Variation", "type": "variation"},
  {"name": "Bursting Magma", "category": "Variation", "type": "variation"},
  {"name": "Distant Tears", "category": "Variation", "type": "variation"},
  {"name": "Radiant Variant", "category": "Variation", "type": "variation"},
  {"name": "Frigid Touch", "category": "Variation", "type": "variation"},
  {"name": "Wandering Witch", "category": "Variation", "type": "variation"},
  {"name": "Golden Toad", "category": "Variation", "type": "variation"},
  {"name": "Prince", "category": "Variation", "type": "variation"},
  {"name": "White Cliff Remnants", "category": "Variation", "type": "variation"},
  {"name": "Fluffy Curse", "category": "Variation", "type": "variation"},
  {"name": "Infrasonic Illusion", "category": "Variation", "type": "variation"},
  {"name": "Spring's Return", "category": "Variation", "type": "variation"},
  {"name": "Fool's Memory", "category": "Variation", "type": "variation"},
  {"name": "Light Rain", "category": "Variation", "type": "variation"},
  {"name": "Childlike Whimsy", "category": "Variation", "type": "variation"},
  {"name": "Radiance", "category": "Variation", "type": "variation"},
  {"name": "Fine Brew", "category": "Variation", "type": "variation"},
  {"name": "Gold Lightning", "category": "Variation", "type": "variation"},
  {"name": "Prototype", "category": "Variation", "type": "variation"},
  {"name": "Witch's Beloved", "category": "Variation", "type": "variation"},
  {"name": "Star Devourer", "category": "Variation", "type": "variation"},
  {"name": "Malevolent Sun", "category": "Variation", "type": "variation"},
  {"name": "Christmas Spirit", "category": "Variation", "type": "variation"},
  {"name": "Chaosaurus", "category": "Chaos", "type": "variation"},
  {"name": "Chaos Mr. Wish", "category": "Chaos", "type": "variation"},
  {"name": "Chaos Snowsprite", "category": "Chaos", "type": "variation"},
  {"name": "Chaos Cat", "category": "Chaos", "type": "variation"},
  {"name": "Starfall Inversion", "category": "Variation", "type": "variation"},
  {"name": "Lunar Oracle", "category": "Variation", "type": "variation"},
  {"name": "Aberrant Progeny", "category": "Variation", "type": "variation"},
  {"name": "Youthful heart(red)", "category": "Variation", "type": "variation"},
  {"name": "Optimism-Extra Large", "category": "Variation", "type": "variation"}
];
