window.PRODUCTS = [
    {
        "id": 1,
        "image": "images/Atomic Lighter.png",
        "name": "Atomic lighter",
        "type": "Starfall",
        "generalTrait": "Starfall Inversion",
        "combatTerriCraft": "Waste Not",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Crit Damage",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 2,
        "image": "images/By-the-Wind.png",
        "name": "By-the-Wind",
        "type": "Lunar",
        "generalTrait": "Frigid Touch",
        "combatTerriCraft": "Lunar Oracle",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 3,
        "image": "images/By-the-Wind2.png",
        "name": "By-the-Wind",
        "type": "Variant",
        "generalTrait": "Frigid Touch",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Physical DMG Bonus",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 4,
        "image": "images/Chaos Mini Wonder.png",
        "name": "Chaos Mini Wonder",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 5,
        "image": "images/Chaos Mini Wonder.png",
        "name": "Chaos Mini Wonder",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 6,
        "image": "images/Chaos Mr. Wish.png",
        "name": "Chaos Mr. Wish",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 7,
        "image": "images/Chaos Mr. Wish.png",
        "name": "Chaos Mr. Wish",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 8,
        "image": "images/Chaos Mr. Wish.png",
        "name": "Chaos Mr. Wish",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Crit Damage",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 9,
        "image": "images/Chaos Snowsprite.png",
        "name": "Chaos Snowsprite",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 10,
        "image": "images/Chaosaurus.png",
        "name": "Chaosaurus",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 4,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 11,
        "image": "images/Chaosaurus.png",
        "name": "Chaosaurus",
        "type": "Chaos",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 1,
        "price": 200,
        "status": "In Stock"
    },
    {
        "id": 12,
        "image": "images/Chaotic Extradimensional Cat.png",
        "name": "Chaotic Extradimensional Cat",
        "type": "Chaos",
        "generalTrait": "Optimist",
        "combatTerriCraft": "A World of Charm",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "HP",
        "stock": 2,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 13,
        "image": "images/Chaotic Extradimensional Cat.png",
        "name": "Chaotic Extradimensional Cat",
        "type": "Chaos",
        "generalTrait": "Rise and Shine 5",
        "combatTerriCraft": "A World of Charm",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "HP Percentage",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 14,
        "image": "images/Doctor Raven.png",
        "name": "Doctor Raven",
        "type": "Normal",
        "generalTrait": "Optimist",
        "combatTerriCraft": "A World of Charm",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "HP",
        "stock": 1,
        "price": 200,
        "status": "In Stock"
    },
    {
        "id": 15,
        "image": "images/Electric Eel.png",
        "name": "Electric Eel",
        "type": "Normal",
        "generalTrait": "Rise and Shine 5",
        "combatTerriCraft": "Anti-Burnout",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 3,
        "price": 100,
        "status": "In Stock"
    },
    {
        "id": 16,
        "image": "images/Flame Essence.png",
        "name": "Flame Essence",
        "type": "Variant",
        "generalTrait": "Prince",
        "combatTerriCraft": "Devoted laborer",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "HP Percentage",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 17,
        "image": "images/Growshroom.png",
        "name": "Growshroom",
        "type": "Variant",
        "generalTrait": "Optimism-Extra Large",
        "combatTerriCraft": "Sweet Talk",
        "deviatedTrait": "Herbivore",
        "scpTrait": "HP",
        "stock": 6,
        "price": 100,
        "status": "In Stock"
    },
    {
        "id": 18,
        "image": "images/Invincible Sun.png",
        "name": "Invincible Sun",
        "type": "Starfall",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 19,
        "image": "images/Invincible Sun.png",
        "name": "Invincible Sun",
        "type": "Starfall",
        "generalTrait": "Infrasonic Illusion",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 20,
        "image": "images/Lonewolf Whisper.png",
        "name": "Lonewolf\"s Whisper",
        "type": "Lunar",
        "generalTrait": "Distant Tears",
        "combatTerriCraft": "Lunar Oracle",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Physical DMG Bonus",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 21,
        "image": "images/Lonewolf Whisper.png",
        "name": "Lonewolf\"s Whisper",
        "type": "Lunar",
        "generalTrait": "Bursting Magma",
        "combatTerriCraft": "Lunar Oracle",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Crit Damage",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 22,
        "image": "images/Mini Feaster.png",
        "name": "Mini Feaster",
        "type": "Starfall",
        "generalTrait": "Star Devourer",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 2,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 23,
        "image": "images/Mini Feaster.png",
        "name": "Mini Feaster",
        "type": "Starfall",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 2,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 24,
        "image": "images/Mini Feaster2.png",
        "name": "Mini Feaster",
        "type": "Variant",
        "generalTrait": "Star Devourer",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack Percentage",
        "stock": 1,
        "price": 200,
        "status": "In Stock"
    },
    {
        "id": 25,
        "image": "images/Mini Wonder.png",
        "name": "Mini Wonder",
        "type": "Starfall",
        "generalTrait": "Bursting Magma",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 1,
        "price": 250,
        "status": "In Stock"
    },
    {
        "id": 26,
        "image": "images/Nutcracker.png",
        "name": "Nutcracker",
        "type": "Variant",
        "generalTrait": "Infrasonic Illusion",
        "combatTerriCraft": "Silver Gentleman",
        "deviatedTrait": "Precision Moment",
        "scpTrait": "HP",
        "stock": 4,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 27,
        "image": "images/Polar Jelly.png",
        "name": "Polar Jelly",
        "type": "Starfall",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 28,
        "image": "images/Polar Jelly.png",
        "name": "Polar Jelly",
        "type": "Starfall",
        "generalTrait": "Radiant Variant",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 1,
        "price": 250,
        "status": "In Stock"
    },
    {
        "id": 29,
        "image": "images/Pyro Dino.png",
        "name": "Pyro Dino",
        "type": "Lunar",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Lunar Oracle",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 2,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 30,
        "image": "images/Rainman1.png",
        "name": "Rain Man",
        "type": "Variant",
        "generalTrait": "Youthful heart(red)",
        "combatTerriCraft": "Anti-Burnout",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 31,
        "image": "images/Rainman2.png",
        "name": "Rain Man",
        "type": "Variant",
        "generalTrait": "Childlike Whimsy(green)",
        "combatTerriCraft": "Devoted laborer",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 32,
        "image": "images/Shattered Maiden.png",
        "name": "Shattered Maiden",
        "type": "Variant",
        "generalTrait": "Wandering Witch",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 33,
        "image": "images/Snowsprite.png",
        "name": "Snowsprite",
        "type": "Lunar",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Lunar Oracle",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Reduction",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 34,
        "image": "images/Snowsprite.png",
        "name": "Snowsprite",
        "type": "Lunar",
        "generalTrait": "Spring\"s Return",
        "combatTerriCraft": "Lunar Oracle",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 35,
        "image": "images/Snowsprite.png",
        "name": "Snowsprite",
        "type": "Variant",
        "generalTrait": "Spring\"s Return",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 36,
        "image": "images/Soul Summoner.png",
        "name": "Soul Summoner",
        "type": "Normal",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 37,
        "image": "images/The Digby Boy.png",
        "name": "The Digby Boy",
        "type": "Starfall",
        "generalTrait": "Starfall Inversion",
        "combatTerriCraft": "Devoted laborer",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 38,
        "image": "images/Voodoo Doll2.png",
        "name": "Voodoo doll",
        "type": "Starfall",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 39,
        "image": "images/Voodoo Doll2.png",
        "name": "Voodoo doll",
        "type": "Variant",
        "generalTrait": "Fluffy Curse",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 40,
        "image": "images/Voodoo Doll2.png",
        "name": "Voodoo Doll",
        "type": "Variant",
        "generalTrait": "Fluffy Curse",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 41,
        "image": "images/Voodoo Doll2.png",
        "name": "Voodoo Doll",
        "type": "Variant",
        "generalTrait": "Fluffy Curse",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Crit Rate",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 42,
        "image": "images/Voodoo Doll2.png",
        "name": "Voodoo doll",
        "type": "Variant",
        "generalTrait": "Fluffy Curse",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 1,
        "price": 100,
        "status": "In Stock"
    },
    {
        "id": 43,
        "image": "images/Whalepup.png",
        "name": "Whalepup",
        "type": "Normal",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Crit Damage",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 44,
        "image": "images/Whalepup.png",
        "name": "Whalepup",
        "type": "Normal",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 1,
        "price": 150,
        "status": "In Stock"
    },
    {
        "id": 45,
        "image": "images/Zapamander.png",
        "name": "Zapamander",
        "type": "Starfall",
        "generalTrait": "Starfall Inversion",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "HP",
        "stock": 2,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 46,
        "image": "images/Zapamander.png",
        "name": "Zapamander",
        "type": "Starfall",
        "generalTrait": "Starfall Inversion",
        "combatTerriCraft": "Psychic Kid",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Elemental DMG Bonus",
        "stock": 5,
        "price": 350,
        "status": "In Stock"
    },
    {
        "id": 47,
        "image": "images/Zapcam.png",
        "name": "Zapcam",
        "type": "Lunar",
        "generalTrait": "Lunar Oracle",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack Percentage",
        "stock": 2,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 48,
        "image": "images/Zapcam2.png",
        "name": "ZapCam",
        "type": "Lunar",
        "generalTrait": "Lunar Oracle",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 49,
        "image": "images/Zapcam2.png",
        "name": "ZapCam",
        "type": "Lunar",
        "generalTrait": "Lunar Oracle",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Physical DMG Bonus",
        "stock": 1,
        "price": 300,
        "status": "In Stock"
    },
    {
        "id": 50,
        "image": "images/Zapcam2.png",
        "name": "ZapCam",
        "type": "Variant",
        "generalTrait": "Fool\"s Memory",
        "combatTerriCraft": "Crack Shot",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "",
        "stock": 1,
        "price": 100,
        "status": "In Stock"
    },
    {
        "id": 51,
        "image": "images/Enchanting Void.png",
        "name": "Enchanting Void",
        "type": "Starfall",
        "generalTrait": "Power Rewind 2",
        "combatTerriCraft": "Starfall Inversion",
        "deviatedTrait": "Moonlight Assault",
        "scpTrait": "Attack",
        "stock": 1,
        "price": 350,
        "status": "In Stock"
    }
];
