// Traits Data - Complete List
const traitsData = [
  {"name": "Upper Hand", "description": "When Deviant Power drops to 0, automatically consume Mood to recover Deviant Power.", "category": "Global", "type": "positive", "source": "Global", "slot": 1},
  {"name": "Stable Energy", "description": "Max Deviant Power +30%", "category": "Global", "type": "positive", "source": "Global", "slot": 1},
  {"name": "Stable Vitality", "description": "Max Mood +30%", "category": "Global", "type": "positive", "source": "Global", "slot": 1},
  {"name": "Optimist 5", "description": "Max Mood +35%", "category": "Global", "type": "positive", "source": "Global", "slot": 1},
  {"name": "Covert Energy 5", "description": "Max Deviant Power +35%", "category": "Global", "type": "positive", "source": "Global", "slot": 1},
  {"name": "Power Rewind 2", "description": "Deviant Power recovery speed +10%", "category": "Global", "type": "positive", "source": "Global", "slot": 1},
  {"name": "Rise and Shine 5", "description": "Mood recovery speed +25%", "category": "Global", "type": "positive", "source": "Global", "slot": 1},
  {"name": "Growing Pains 3", "description": "Max Deviant Power +50%; Mood recovery speed -5% ", "category": "Global", "type": "mixed", "source": "Global", "slot": 1},
  {"name": "Cheer Up 3", "description": "Max Mood +50%; Deviant Power recovery speed -5%", "category": "Global", "type": "mixed", "source": "Global", "slot": 1},
  {"name": "Worn-out 2", "description": "Max Deviant Power -10%", "category": "Global", "type": "negative", "source": "Global", "slot": 1},
  {"name": "Feeling Blue 2", "description": "Max Mood -10%", "category": "Global", "type": "negative", "source": "Global", "slot": 1},

  {"name": "Psychic Kid", "description": "Having it fight alongside grants Status DMG +5%", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Crack Shot", "description": "Having it fight alongside grants Weapon DMG +5%", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Heavy and Solid", "description": "Higher Load grants higher DMG Reduction for torso, up to +15%", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Run Fast", "description": "Syncing with this Deviation grants Movement Speed +5%", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Power King", "description": "Syncing with it grants Max Load +25, Movement Speed -5%", "category": "Combat", "type": "mixed", "source": "Combat Deviation", "slot": 2},
  {"name": "Brute Force", "description": "Syncing with it grants Max Load +15, Movement Speed -5%", "category": "Combat", "type": "mixed", "source": "Combat Deviation", "slot": 2},
  {"name": "Long Distance Runner", "description": "Syncing with it grants Stamina consumption -20%, Movement Speed -10%", "category": "Combat", "type": "mixed", "source": "Combat Deviation", "slot": 2},
  {"name": "Save Energy", "description": "Syncing with it grants Stamina consumption -10%, Movement Speed -5%", "category": "Combat", "type": "mixed", "source": "Combat Deviation", "slot": 2},
  {"name": "Vegatative Calm", "description": "Syncing with it grants Max Stamina +15, Movement Speed -5%", "category": "Combat", "type": "mixed", "source": "Combat Deviation", "slot": 2},
  {"name": "Beast of Burden", "description": "Syncing with it grants Max Load +8", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "City Folk", "description": "Syncing with it grants Max Load +15 when exploring Settlements", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Durability", "description": "Syncing with it grants Stamina Consumption -5%", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Move More, Live Better", "description": "Securement Progress +1 per 8 seconds when sprinting", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Street Rascal", "description": "Syncing with it grants Movement Speed +10% in Settlements", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Two-Shift System", "description": "Syncing with it grants Max Load +16 at daytime, and Movement Speed +12% at night", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Stay Indoors", "description": "Syncing with it grants +8% Stamina Consumption in Settlements", "category": "Combat", "type": "negative", "source": "Combat Deviation", "slot": 2},
  {"name": "Wellbeing", "description": "Syncing with this Deviation grants Max Stamina +10", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 2},
  {"name": "Sedantary", "description": "Syncing with it grants Max Load -8 when exploring Settlements", "category": "Combat", "type": "negative", "source": "Combat Deviation", "slot": 2},
  {"name": "Lighten Your Mind", "description": "Lower Load grants higher DMG Reduction for head, up to +15%", "category": "Combat", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Elemental DMG Reduction", "description": "Elemental DMG Reduction +12% / +17% / +22% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Physical DMG Reduction", "description": "Physical DMG Reduction +12% / +17% / +22% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Elemental DMG Bonus", "description": "Elemental DMG Bonus +15% / +21% / +27% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Physical DMG Bonus", "description": "Physical DMG Bonus +15% / +21% / +27% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Attack", "description": "Attack +28 / +38 / +50 (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Attack Percentage", "description": "Attack +10% / +14% / +18% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "HP", "description": "HP +2350 / +3300 / +4250 (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "HP Percentage", "description": "HP +10% / +14% / +18% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Crit Damage", "description": "Crit Damage +36% / +50% / +64% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},
  {"name": "Crit Rate", "description": "Crit Rate +18% / +25% / +32% (Levels 1-3)", "category": "all", "type": "positive", "source": "Combat Deviation", "slot": 4},

  {"name": "Anti-Burnout", "description": "When dormant (regaining Power), 20% chance others receive Power +5", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Dream Wild", "description": "When dormant (regaining Power), 10% chance others receive Power +10", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "A World of Charm", "description": "When dormant (regaining Mood), 10% chance others receive Mood +20", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Sweet Talk", "description": "When dormant (regaining Mood), 20% chance others receive Mood +5", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Hydrophilic", "description": "When resting by water, Energy Recovery Speed +30%", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Devoted laborer", "description": "Mood and Power consumption speed +20% (Works 20% faster)", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},
  {"name": "Workaholic", "description": "Mood and Power consumption speed +10% (Works 10% faster)", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},
  {"name": "Water Dormancy", "description": "When resting by water, Mood Recover Speed +30%", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Voluntary Overtime", "description": "10% chance that working does not consume Mood", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Living Map", "description": "Resource production interval -5%", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Stardust Affinity", "description": "When working in Pollution Zone, 20% chance to not consume Mood", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "OnePlus", "description": "5% chance to bring back rare crystals. Return time increased.", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},
  {"name": "Imperfect Endless Motion", "description": "10% chance that working does not consume Deviant Power", "category": "Territory", "type": "positive", "source": "Territory Deviation", "slot": 2},
  {"name": "Lazy Bones", "description": "Working speed -5%", "category": "Territory", "type": "negative", "source": "Territory Deviation", "slot": 2},
  {"name": "Panovision", "description": "Working speed -10%", "category": "Territory", "type": "negative", "source": "Territory Deviation", "slot": 2},
  {"name": "Slacking Off", "description": "Mood and Power consumption speed +5%", "category": "Territory", "type": "negative", "source": "Territory Deviation", "slot": 2},
  {"name": "Baffling Behavior", "description": "When Power decreases, 10% chance other Deviations also lose Power.", "category": "Territory", "type": "negative", "source": "Territory Deviation", "slot": 2},
  {"name": "Holding the Team Back", "description": "When Mood decreases, 10% chance other Deviations also lose Mood.", "category": "Territory", "type": "negative", "source": "Territory Deviation", "slot": 2},
  {"name": "Heartthrob", "description": "When Power decreases, 10% chance others lose Power. When dormant, 10% chance others gain +5 Mood.", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},
  {"name": "Snooze Afficionado", "description": "When Mood decreases, 10% chance others lose Mood. When dormant, 10% chance others gain +5 Power.", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},
  {"name": "Toxicologist", "description": "Territorial Deviation may bring back Acid.", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},
  {"name": "An old Hand Knows the Ropes", "description": "Faster Mood/Power consumption, Working Speed +10%.", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},

  {"name": "Waste Not", "description": "Activity Score > 90%, 5% chance to increase others' Power by 10", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Leftover", "description": "Activity Score > 20%, 10% chance to increase others' Power by 1. Energy -20%, Max Storage -20%", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},
  {"name": "Byproduct", "description": "Activity Score > 90%, 10% chance to increase others' Power by 2", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Efficiency Above All", "description": "Crafting speed +20%, Max storage capacity -30%", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},
  {"name": "Stardust Empowerment", "description": "Working in Pollution Zone, 20% chance to not consume Energy", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Speed Up", "description": "Crafting production interval reduced by 10%", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Productivity First", "description": "Crafting production interval reduced by 5%", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Collection +1", "description": "5% chance Crafting output +2, Crafting speed -20%", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},
  {"name": "Eureka Moment", "description": "1% chance to produce 10 extra units, but interval increased by 50%", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},
  {"name": "The Joy of Slacking Off", "description": "10% chance that crafting consumes 0 Mood, Crafting speed -20%", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},
  {"name": "Unhinged Production", "description": "Activity Score < 20%, consume others' Power by 1 to produce 2 extra units", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},
  {"name": "Unplanned Production", "description": "10% chance crafting consumes 0 Power, Crafting speed -20%", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},
  {"name": "Big Cup", "description": "Limit capacity during Crafting +20%", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Buy 1 Get 2", "description": "5% chance to produce 1 extra unit", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Come As One", "description": "Output +1 for every 1 Territory Deviation in the Territory", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Efficiency First", "description": "Crafting interval reduced by 5%", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Medium Cup", "description": "Max storage capacity +10%", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Mineral Talent", "description": "Within Oil Field radius, 20% chance to increase output by 1", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "One More Bottle", "description": "2% chance to produce 2 extra units", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Out of Scratch", "description": "3% chance to not use up Deviant Power", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Piece of Cake", "description": "5% chance to not use up Activity Score", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Super Big Cup", "description": "Limit capacity during Crafting +30%", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "The Last Night", "description": "Crafting interval reduced by 15%", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Work of Proficiency", "description": "5% chance to not use up Deviant Power", "category": "Crafting", "type": "positive", "source": "Crafting Deviation", "slot": 2},
  {"name": "Clumsy", "description": "5% chance that Crafting Output -1", "category": "Crafting", "type": "negative", "source": "Crafting Deviation", "slot": 2},
  {"name": "No Such Thing As a Small Cup", "description": "Max Storage Capacity -10%", "category": "Crafting", "type": "negative", "source": "Crafting Deviation", "slot": 2},
  {"name": "Lazy", "description": "Crafting speed -10%", "category": "Crafting", "type": "negative", "source": "Crafting Deviation", "slot": 2},
  {"name": "Smooth Sheep Rustler", "description": "When Mood < 20%, consume other Deviations' Power by 5 to generate resources.", "category": "Crafting", "type": "mixed", "source": "Crafting Deviation", "slot": 2},

  {"name": "Moonlight Assault", "description": "At night, Deviant Energy and Mood Recovery rates are increased.", "category": "Animal", "type": "positive", "source": "Wolf", "slot": 3},
  {"name": "Feline Creatures", "description": "Fall damage reduced by 50%, fractures prevented. / Extra Lightweight item.", "category": "Animal", "type": "positive", "source": "Leopard", "slot": 3},
  {"name": "Brute Force Rules", "description": "Dodging/dashing shatters ores/trees. / Chance to double resource output.", "category": "Animal", "type": "positive", "source": "Bear", "slot": 3},
  {"name": "Foul Symbiosis", "description": "10% chance for +1 Acid on kill. / +1 Acid in Pollution Zone.", "category": "Animal", "type": "positive", "source": "Boar", "slot": 3},
  {"name": "Polar Beast", "description": "Temp below 0C, Attack +10% / Mood recovers 10% faster.", "category": "Animal", "type": "positive", "source": "Polar Bear", "slot": 3},
  {"name": "Top Grunt", "description": "No Stamina consumed during gathering. / Converts Mood to Energy at low power.", "category": "Animal", "type": "positive", "source": "Buffalo", "slot": 3},
  {"name": "Nightmare Waters", "description": "Stamina consumption reduced while diving. / Chance to yield extra fish.", "category": "Animal", "type": "positive", "source": "Crocodile", "slot": 3},
  {"name": "Mind Massage", "description": "Sanity gradually recovers when returning to territory.", "category": "Animal", "type": "positive", "source": "Capybara", "slot": 3},
  {"name": "Herbivore", "description": "Nearby herbivores will no longer flee. / Chance to yield additional deviated plant.", "category": "Animal", "type": "positive", "source": "Deer/Goat", "slot": 3},
  {"name": "Pollution Adaptation", "description": "Sanity drops 90% slower in Pollution Zone. / Max Power +15 in Pollution.", "category": "Furniture", "type": "positive", "source": "Modern Toilet", "slot": 3},
  {"name": "Precision Moment", "description": "Increases Mood by 10 and Energy by 10 for all Deviations every hour.", "category": "Furniture", "type": "positive", "source": "Desktop Electronic Clock", "slot": 3},
  {"name": "Master of Temperatures", "description": "Players gain 10 Heat Resist within territory.", "category": "Furniture", "type": "positive", "source": "Any Fan", "slot": 3},
  {"name": "Knights of the Round Table", "description": "Reduces damage taken by this Deviation / Def +5% & Energy drain reduced.", "category": "Furniture", "type": "positive", "source": "Any Table", "slot": 3},
  {"name": "Warm Flame", "description": "Player's Cold Resist +10", "category": "Furniture", "type": "positive", "source": "Candelabra", "slot": 3},
  {"name": "Eureka Moment", "description": "Attacker revealed and DMG -10%. / No light required for securement.", "category": "Furniture", "type": "positive", "source": "Lamp / Signal Light", "slot": 3},
  {"name": "Extra Load", "description": "Max Load +20. / Storage +15%.", "category": "Furniture", "type": "positive", "source": "Any Carton", "slot": 3},
  {"name": "Music Resonance", "description": "Will not require radio for securement box", "category": "Furniture", "type": "positive", "source": "Jukebox", "slot": 3},
  {"name": "Clean and Hygienic", "description": "Sanity automatically recovers to 20% when low", "category": "Furniture", "type": "positive", "source": "Sink", "slot": 3},
  {"name": "Neon Flicker", "description": "For every 'Neon Flicker' in territory, max Mood all Deviations +1", "category": "Furniture", "type": "positive", "source": "Sign (Like)", "slot": 3},
  
  {"name": "Gilded Oracle", "description": "May bring back additional ores.", "category": "Territory", "type": "mixed", "source": "The Digby Boy", "slot": 2},
  {"name": "Wild Wood Spirit", "description": "When bringing back resources, 5% chance to bring a deviated flower.", "category": "Territory", "type": "mixed", "source": "Territory Deviation", "slot": 2},

  {"name": "Milk Sugar", "description": "Gains Max Mood 35%", "category": "Variation", "type": "variation", "source": "Festering Gel", "slot": 1},
  {"name": "Marine Star", "description": "Each reload gives either 5% Weapon DMG bonus or 5% Status DMG at random.", "category": "Variation", "type": "variation", "source": "Festering Gel", "slot": 1},
  {"name": "Spring Rose", "description": "When synced +20% more healing during the day +10% at night", "category": "Variation", "type": "variation", "source": "Festering Gel", "slot": 1},
  {"name": "Ancient Scroll", "description": "Gains Max Energy 40%", "category": "Variation", "type": "variation", "source": "Butterfly Emissary", "slot": 1},
  {"name": "Glistening Blue", "description": "When synced, hitting a Weakspot increases Deviation Power by 1 (CD: 3s).", "category": "Variation", "type": "variation", "source": "Butterfly Emissary", "slot": 2},
  {"name": "Starry Night", "description": "When synced, deal +6% more damage at night +3% during day", "category": "Variation", "type": "variation", "source": "Butterfly Emissary", "slot": 2},
  {"name": "Aquarius", "description": "Gains Mood Recovery Speed +30%", "category": "Variation", "type": "variation", "source": "Fetch-A-Lot Bunny", "slot": 1},
  {"name": "Gluttonous Bunny", "description": "Gains Energy Recovery Speed +15%", "category": "Variation", "type": "variation", "source": "Fetch-A-Lot Bunny", "slot": 1},
  {"name": "Dark Rebel", "description": "When exploring, has a chance to bring back Acid.", "category": "Variation", "type": "variation", "source": "Fetch-A-Lot Bunny", "slot": 2},
  {"name": "Alice", "description": "When exploring, has a 10% chance to bring back Acid.", "category": "Variation", "type": "variation", "source": "Fetch-A-Lot Bunny", "slot": 2},
  {"name": "Violet Robe", "description": "Gains Max Energy 40%", "category": "Variation", "type": "variation", "source": "Grumpy Bulb", "slot": 1},
  {"name": "Extra Large", "description": "Gains Max Mood +40%", "category": "Variation", "type": "variation", "source": "Growshroom", "slot": 1},
  {"name": "Green Touch", "description": "When working in Pollution Zone, has 25% chance to not consume Energy.", "category": "Variation", "type": "variation", "source": "Growshroom", "slot": 2},
  {"name": "Green Field", "description": "Energy Max Limit increased by 10.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Copper Green", "description": "Max Deviant Power +7%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Tin Soldier", "description": "Gains Max Energy +35", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Twisted Fairy Tale", "description": "Gains Max Energy +40%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Displaced Fairy Tale", "description": "Gains Max Energy +40%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Wood Yellow", "description": "Mood Recovery Speed +7%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Clear Lake", "description": "Deviant Power Recovery Speed +7%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Purple (Power Rewind)", "description": "Gains Energy Recovery Speed +15%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Date Brown", "description": "Max Mood +7%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Golden Era", "description": "Gains Max Mood +35", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 1},
  {"name": "Silver Gentleman", "description": "When recovering Mood while dormant, 25% chance to restore 10 Mood to Territory Deviations.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Diamond Duke", "description": "5% chance to not consume Deviant Power when working in Pollution Zone.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Diamond Count", "description": "5% chance not consume Energy Territory Deviations, in Pollution Zone", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Ocean Blue", "description": "When working in Pollution Zone, 30% chance not to consume Mood.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Christmas", "description": "While working, energy and Mood consumption interval +5%.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Sugar Guard", "description": "There is a 3% chance that working does not consume Mood.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Admiral", "description": "There is a 3% chance that working does not consume Deviant Power.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Elegant Purple", "description": "When activated and working, 20% chance not to consume Deviant Power.", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Dappled Light", "description": "When working, gains Energy and Mood consumption interval +20%", "category": "Variation", "type": "variation", "source": "Nutcracker", "slot": 2},
  {"name": "Good Fortune", "description": "Gains Max Mood +40%", "category": "Variation", "type": "variation", "source": "Extradimensional Cat", "slot": 1},
  {"name": "Moonlit Jewels", "description": "When recovering Energy dormant, 20% chance to restore 15 Power to other Territory Deviations.", "category": "Variation", "type": "variation", "source": "Extradimensional Cat", "slot": 2},
  {"name": "Heavy Ginger", "description": "When resting by water, gains Mood Recovery Speed +35%", "category": "Variation", "type": "variation", "source": "Extradimensional Cat", "slot": 2},
  {"name": "Emerald", "description": "Gains Energy Recovery Speed +10%", "category": "Variation", "type": "variation", "source": "The Digby Boy", "slot": 1},
  {"name": "Fortune Dice", "description": "A dice that never lets you down. Max Deviant Power +6%.", "category": "Variation", "type": "variation", "source": "The Digby Boy", "slot": 1},
  {"name": "Pure Gold", "description": "When exploring, has a chance to bring back additional ores.", "category": "Variation", "type": "variation", "source": "The Digby Boy", "slot": 2},
  {"name": "Prism", "description": "When activated and working, has a 15% chance to not consume Mood.", "category": "Variation", "type": "variation", "source": "The Digby Boy", "slot": 2},
  {"name": "Radiant Flourish", "description": "Increases Max Mood 8%.", "category": "Variation", "type": "variation", "source": "Buzzy Bee", "slot": 1},
  {"name": "Pumpkin Lantern", "description": "Max Deviant Power +10%.", "category": "Variation", "type": "variation", "source": "Buzzy Bee", "slot": 1},
  {"name": "Pharaoh", "description": "Gains Mood Recovery Speed +30%", "category": "Variation", "type": "variation", "source": "Enchanting Void", "slot": 1},
  {"name": "Bursting Magma", "description": "Gains Max Energy +40%", "category": "Variation", "type": "variation", "source": "Lonewolf / By-The-Wind / Mini Wonder", "slot": 1},
  {"name": "Distant Tears", "description": "Gains Max Energy +40%", "category": "Variation", "type": "variation", "source": "Lonewolf's Whisper", "slot": 1},
  {"name": "Radiant Variant", "description": "Gains Max Mood +7%", "category": "Variation", "type": "variation", "source": "Lonewolf / Polar Jelly", "slot": 1},
  {"name": "Frigid Touch", "description": "Gains Energy Recovery Speed +15%", "category": "Variation", "type": "variation", "source": "By-The-Wind", "slot": 1},
  {"name": "Wandering Witch", "description": "Max Deviant Power +10%", "category": "Variation", "type": "variation", "source": "Shattered Maiden", "slot": 1},
  {"name": "Golden Toad", "description": "Gains Mood Recovery Speed +20%", "category": "Variation", "type": "variation", "source": "Flame Essence", "slot": 1},
  {"name": "Prince", "description": "Gains Max Mood +35%", "category": "Variation", "type": "variation", "source": "Flame Essence", "slot": 1},
  {"name": "White Cliff Remnants", "description": "Gains Max Mood +35%", "category": "Variation", "type": "variation", "source": "Space Turner", "slot": 1},
  {"name": "Fluffy Curse", "description": "Gains Energy Recovery Speed +10%", "category": "Variation", "type": "variation", "source": "Voodoo Doll", "slot": 1},
  {"name": "Infrasonic Illusion", "description": "Gains Energy Recovery Speed +10% / Mood +20% depending on source.", "category": "Variation", "type": "variation", "source": "Various", "sourceDeviations": ["Nutcracker", "H37", "Paper Doll", "Festering Gel", "Space Turner", "Gingerbread House", "Pup Buddy", "Party Monkey", "Disco Ball", "Snow Globe", "Electric Eel", "Wish Box", "Fetch-A-Lot Bunny", "Dr. Teddy", "Invincible Sun"], "slot": 1},
  {"name": "Spring's Return", "description": "Gains Max Mood +35%", "category": "Variation", "type": "variation", "source": "Snowsprite", "slot": 1},
  {"name": "Fool's Memory", "description": "Gains Energy Recovery Speed +10%", "category": "Variation", "type": "variation", "source": "Zapcam", "slot": 1},
  {"name": "Light Rain", "description": "Gains Energy Recovery Speed +15%", "category": "Variation", "type": "variation", "source": "Rain Man", "slot": 1},
  {"name": "Childlike Whimsy", "description": "Gains Energy Recovery Speed +30%", "category": "Variation", "type": "variation", "source": "Rain Man", "slot": 1},
  {"name": "Radiance", "description": "Gains Max Energy +40%", "category": "Variation", "type": "variation", "source": "Tar Pudding", "slot": 1},
  {"name": "Fine Brew", "description": "Gains Energy Recovery Speed +10%", "category": "Variation", "type": "variation", "source": "Tar Pudding", "slot": 1},
  {"name": "Gold Lightning", "description": "Gains Energy Recovery Speed +15%", "category": "Variation", "type": "variation", "source": "Electric Eel / Atomic Snail", "slot": 1},
  {"name": "Prototype", "description": "Gains Energy Recovery Speed +10%", "category": "Variation", "type": "variation", "source": "H37", "slot": 1},
  {"name": "Witch's Beloved", "description": "Gains Mood Recovery Speed +20%", "category": "Variation", "type": "variation", "source": "Paper Doll", "slot": 1},
  {"name": "Star Devourer", "description": "Energy Recovery Speed +10%", "category": "Variation", "type": "variation", "source": "Mini Feaster", "slot": 1},
  {"name": "Malevolent Sun", "description": "Mood Recovery Speed +20%", "category": "Variation", "type": "variation", "source": "Invincible Sun", "slot": 1},
  {"name": "Christmas Spirit", "description": "Max Energy +10%, Energy recovery speed +5%", "category": "Variation", "type": "variation", "source": "Dr. Teddy / Chefosaurus Rex", "slot": 1},
  

  {"name": "Lunar Oracle", "description": "Weapon DMG +5% (+7.5% when sanity <30%)", "category": "Variation", "type": "variation", "source": "Lonewolf's Whisper", "slot": 2},
  {"name": "Lunar Oracle", "description": "Gliding speed modifier (Horizontal +10%, Downward -20%)", "category": "Variation", "type": "variation", "source": "By-The-Wind", "slot": 2},
  {"name": "Lunar Oracle", "description": "Restores 1 Power/8s (1.5 when sanity <30%)", "category": "Variation", "type": "variation", "source": "Festering Gel", "slot": 2},
  {"name": "Lunar Oracle", "description": "Status DMG +5% (+7.5% when sanity <30%)", "category": "Variation", "type": "variation", "source": "Pyro Dino / Snowsprite", "slot": 2},
  {"name": "Lunar Oracle", "description": "Weapon DMG +5% (+7.5% when sanity <30%)", "category": "Variation", "type": "variation", "source": "Zapcam", "slot": 1},
  {"name": "Lunar Oracle", "description": "Melee DMG +10% (+15% when sanity <30%)", "category": "Variation", "type": "variation", "source": "Zeno Purifier", "slot": 2},
  {"name": "Lunar Oracle", "description": "Resource production interval -15%", "category": "Variation", "type": "variation", "source": "Atomic Snail", "slot": 1},
  {"name": "Lunar Oracle", "description": "While working, energy and Activity Score consumption interval +20%", "category": "Variation", "type": "variation", "source": "Electric Eel", "slot": 1},
  {"name": "Starfall Inversion", "description": "Melee DMG +5% (+7.5% when airborne)", "category": "Variation", "type": "variation", "source": "Enchanting Void", "slot": 2},
  {"name": "Starfall Inversion", "description": "Blaze Elemental DMG +5% (+7.5% when airborne)", "category": "Variation", "type": "variation", "source": "Invincible Sun", "slot": 2},
  {"name": "Starfall Inversion", "description": "Status DMG +5% (+7.5% when airborne)", "category": "Variation", "type": "variation", "source": "Mini Feaster", "slot": 2},
  {"name": "Starfall Inversion", "description": "Head/Torso DMG reduction +5% (+7.5% when airborne)", "category": "Variation", "type": "variation", "source": "Mini Wonder", "slot": 2},
  {"name": "Starfall Inversion", "description": "Frost Elemental DMG +5% (+7.5% when airborne)", "category": "Variation", "type": "variation", "source": "Polar Jelly", "slot": 2},
  {"name": "Starfall Inversion", "description": "Restores 1 Power/8s (1.5 when airborne)", "category": "Variation", "type": "variation", "source": "Voodoo Doll", "slot": 2},
  {"name": "Starfall Inversion", "description": "Electric Elemental DMG +5%(+7.5% when airborne)", "category": "Variation", "type": "variation", "source": "Zapamander", "slot": 1},
  {"name": "Starfall Inversion", "description": "May bring back additional ores.", "category": "Variation", "type": "variation", "source": "The Digby Boy", "slot": 1},
  {"name": "Starfall Inversion", "description": "Has a 20% chance to yield 1 additional resource.", "category": "Variation", "type": "variation", "source": "Atomic Lighter", "slot": 1},

  {"name": "Aberrant Progeny", "description": "Has a 30% chance of not consuming Mood when in a Pollution Zone.", "category": "Variation", "type": "variation", "source": "Rain Man", "slot": 1},
  {"name": "Aberrant Progeny", "description": "Has a 30% chance of yielding +1 resource when in a Pollution Zone.", "category": "Variation", "type": "variation", "source": "Snow Globe", "slot": 1},
  {"name": "Aberrant Progeny", "description": "When recovering Energy while dormant, has a 20% change of restoring 15 Deviant Power to other Territory Deviations.", "category": "Variation", "type": "variation", "source": "Rebecca", "slot": 1},
  {"name": "Aberrant Progeny", "description": "Has a 10% chance of not consuming Deviant Power when in a Pollution Zone.", "category": "Variation", "type": "variation", "source": "Growshroom", "slot": 1},
  {"name": "Aberrant Progeny", "description": "Player damage taken is reduced by 15%, with 50% more effect while in Pollution Zones.", "category": "Variation", "type": "variation", "source": "Dr. Teddy", "slot": 1},
  {"name": "Aberrant Progeny", "description": "Has a 30% chance of yielding +1 resource when in a Pollution Zone.", "category": "Variation", "type": "variation", "source": "Upper World Spawn", "slot": 1}

];
